# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hscore Matrix computation
#'
#' @param mat a numerical matrix
#' @export
HscoreC <- function(mat) {
    .Call(`_funloci_HscoreC`, mat)
}

